spring:
  application:
    name: easy_verify_spring_boot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_verify?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: root@123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
    port: 465
  aop:
    auto: true
    proxy-target-class: true

server:
  port: 5200
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 随机编码 改了之后所有的url加密字段都会改变
encrypt:
  base64: Yv49zklFRh0V2Km5uSoqOZjbP6pywdDC/e7EgUGWM+XrHAaLxI3i1BTctJnQNf8s

